### ISSUE TITLE
Update Module 4 scripts

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/rnaseq_tutorial_wiki#11]
Before merging the forthcoming hisat2 PR, we need to have updates to the following files in the main rnaseq_tutorial github repo.  These files are not part of the actual wiki:

- [ ] Tutorial_Module4_Part2_CummeRbund.R
- [ ] Tutorial_Module4_Part3_Supplementary_R.R
- [ ] Tutorial_Module4_ERCC_DE.R
- [ ] Tutorial_Module4_Part4_edgeR.R

**Comment by jasonwalker80** [comment]
This issue is resolved for HISAT2, but the same updates are required(even more extensive) to run on stringtie/ballgown files instead of cufflinks/cuffdiff

**Comment by obigriffith** [comment]
As a starting point we should decide whether we need all these. For example, we only need to recreate one of part 2/3 to do some basic visualization of DE results. Isn't ballgown meant to replace these? The edgeR tutorial shouldn't change much if you still have a simple transcript/gene + count result. I think you created the ERCC_DE.R script? Also very simple right?

**Comment by jasonwalker80** [comment]
See the rnaseq_tutorial issue here:
https://github.com/griffithlab/rnaseq_tutorial/issues/4
