### ISSUE TITLE
Anyone can edit the Wiki

### ISSUE THREAD

**Issue by paulklemm** [griffithlab/rnaseq_tutorial_wiki#33]
Anyone on Github can edit [the Wiki](https://github.com/griffithlab/rnaseq_tutorial/wiki) using the `Edit` button on the upper right.

I was surprised I could change the links Flexbar project to the current home on github on the page [Adapter-Trim](https://github.com/griffithlab/rnaseq_tutorial/wiki/Adapter-Trim). I only afterwards learned that the proper way is to make a pull request on the [rnaseq_tutorial_wiki](https://github.com/griffithlab/rnaseq_tutorial_wiki) repo.

I suggest setting the wiki to read-only to avoid misuse.

**Comment by malachig** [comment]
Yeah, we do have teams, collaborators, etc. set up for this repo.  Probably is a good idea. I have now restricted editing to users in teams with push access only.
