### ISSUE TITLE
Perl or Python one-liners

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/rnaseq_tutorial_wiki#6]
@ahwagner here is an example of a one liner in the tutorial for evaluating the a GTF format file:

`perl -ne 'if ($_ =~ /(gene_id\s\"ENSG\w+\")/){print "$1\n"}' genes_chr22_ERCC92.gtf | sort | uniq | wc -l`

The tutorial describes the Perl one-liner usage.  Did we decide if we were going to switch out all perl references for python equivalents?

**Comment by ahwagner** [comment]
Python is not best for doing this sort of task. I have rarely ever seen somebody use it in-line... it really isn't built for that. That said, I think we had talked about how the overhead for learning perl (or Python) was maybe a bit much for the amount of usage we got with it in the tutorials. @obigriffith, what do you think?

**Comment by obigriffith** [comment]
I believe we decided it was not worth reworking these one-liners to Python (not suited). Rather we will overall de-emphasize perl in the course except as a linux tool like any other (grep, awk, sed). But, where there are larger more complex script/programs in perl we might refactor as python.
